create table if not exists public.relatoria_hallazgos (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  fecha_hora text,
  mesa text not null,
  grupo text not null,
  ronda integer,
  relator text not null,
  moderador text,
  hallazgo text not null,
  barrera text,
  barrera_otra text,
  ejemplo text,
  actor text,
  actor_otro text,
  apoyo_solucion text,
  sectorialidad text,
  prioridad text,
  frase_clave text,
  notas text
);

alter table public.relatoria_hallazgos enable row level security;

-- Para un piloto interno simple con la llave pública. Si después se integra autenticación,
-- sustituir estas políticas por reglas ligadas a auth.uid().
create policy "relatoria_select_anon"
on public.relatoria_hallazgos for select
to anon
using (true);

create policy "relatoria_insert_anon"
on public.relatoria_hallazgos for insert
to anon
with check (true);

create policy "relatoria_delete_anon"
on public.relatoria_hallazgos for delete
to anon
using (true);
